CREATE TABLE bet_by_market (
   market_id text,
   id timeuuid,
   account_id bigint,
   bet_id bigint,
   selection_id bigint,
   sport_id bigint,
   state int,
   placed_date timestamp,
   side text,
   absolute_ex_rate decimal,
   avg_price_matched decimal,
   cancelled_date timestamp,
   handicap decimal,
   market_betting_type int,
   matched_date timestamp,
   original_id bigint,
   partner_id int,
   persistence_type text,
   placed_ip text,
   price decimal,
   profit decimal,
   risk_coefficient map<bigint, decimal>,
   risk_detail place_order_risk_detail,
   settled_date timestamp,
   size decimal,
   size_cancelled decimal,
   size_lapsed decimal,
   size_matched decimal,
   size_placed decimal,
   size_remaining decimal,
   size_voided decimal,
   version int,
   PRIMARY KEY (market_id, bet_id, id)
);